### ISSUE TITLE
System provided reboot functionality

### ISSUE THREAD

**Issue by eson57** [domo141/sfos-pkexec-reboot#1]
> (I'd be happy if this program gets obsoleted by system-provided reboot functionality)

There already is a system provided reboot functionality since always I think. Or did I completely misunderstand this?

![Screenshot_20220626_002](https://user-images.githubusercontent.com/2996154/175798893-f2fb9496-432e-41f1-9b7d-b9521c87cb7c.png)

![Screenshot_20220626_001](https://user-images.githubusercontent.com/2996154/175798896-8aed7c7d-ba46-41f5-9742-663c476f1640.png)

**Comment by domo141** [comment]
Thanks, found the button in my developer tools (kehitystyökalut in my menu)

The sentence 'Näytä uudelleenkäynnistysvaihtoehto ylävalikossa' was too hard for me to find or comprehend (although it is very good finnish :D)

Have to update information in openrepos. I wonder whether 'developer tools' is needed for this to be seen
(and even it it was not needed, why that is so hard to find) -- IMO reboot option should be readily available for everyone (but not too easy to be pressed accidentally)

**Comment by eson57** [comment]
It is there, even without developer tools enabled. But I agree it shouldn't be that well hidden.

**Comment by domo141** [comment]
Added Note in README about this option. closing.
